### ISSUE TITLE
ebay.com results in an invalid IP(198.245.95)

### ISSUE THREAD

**Issue by rdthrush** [nullstream/spf_dump#7]
I didn't expect spf_dump.py to generate an invalid IP, ie. only 3 octets.  Here's a summary of what I see:

    python2.7 spf_dump.py ebay.com | grep 198.245.95
    198.245.95.5
    198.245.95
    198.245.95.7

I've put the full results of the following session [here](http://arp.thrush.com/spf/Log.ebay.com.02.txt) :

    dig soa ebay.com +short
    dig txt ebay.com
    dig ebay.com txt +short
    dig ebay.com a +short
    dig ebay.com mx +short
    python2.7 spf_dump_debug.py ebay.com

spf_dump_debug.py is:

    diff -wbu0 spf_dump.py spf_dump_debug.py
        --- spf_dump.py Tue Oct  7 06:42:30 2014
        +++ spf_dump_debug.py   Thu Oct  9 06:46:03 2014
        @@ -77 +77 @@
        -for i in parse(sys.argv[1]):
        +for i in parse(sys.argv[1],debug=True):

**Comment by nullstream** [comment]
Latest revision doesn't have this issue.
Ebay's record has a bit of junk but nothing the tool barfs on:
sean@foo:spf_dump$python spf_dump.py ebay.com
206.165.246.80/29
72.3.237.64/28
66.135.215.134
212.110.10.2
74.112.64.26
204.14.234.64/28
194.64.234.128/27
173.0.84.224/28
80.93.9.10
67.228.50.32/27
54.244.126.193
216.113.175.0/24
96.43.152.64/27
74.63.235.224
mails-1951040932.us-west-2.elb.amazonaws.com.
66.211.184.0/23
64.4.244.64/27
75.126.253.0/24
216.113.172.64/29
136.146.208.16/28
63.104.149.126
210.80.80.136
74.63.231.0/24
182.50.78.64/28
96.43.153.64/27
193.28.178.0/25
85.222.130.32/28
72.3.185.0/24
63.80.14.17
96.43.147.64/28
167.89.0.0/17
220.248.6.124
64.94.204.222
216.177.178.3
203.55.21.0/24
212.147.136.123
216.113.168.128
174.36.92.96/27
173.193.132.0/23
74.63.194.0/24
192.28.128.0/18
62.22.61.131
74.63.202.0/24
198.21.0.0/21
50.31.32.0/19
217.149.33.234
91.211.240.0/24
173.0.94.244/30
63.111.28.137
136.146.210.16/28
136.147.62.32/28
74.63.247.0/24
213.219.8.227
212.208.64.34
103.237.104.0/22
208.115.239.0/24
204.14.232.64/28
72.32.243.0/24
91.194.248.0/23
203.145.57.160/27
67.72.12.30
217.175.194.0/24
69.162.98.0/24
64.68.79.253
185.4.120.0/24
64.4.240.64/27
216.113.172.0/25
206.25.247.155
174.36.80.208/28
199.15.212.0/22
66.135.215.0/24
72.32.154.0/24
74.63.231.144
67.72.12.29
66.211.168.230/31
209.63.28.11
64.127.115.252
208.74.204.0/22
204.13.11.48/30
66.211.161.0/25
216.113.160.0/24
204.14.238.0/27
65.110.161.77
216.113.160.244
217.175.195.0/24
208.115.235.0/24
103.28.42.0/24
216.113.172.68
96.43.148.64/28
12.155.144.75
72.32.217.0/24
163.47.180.0/22
216.113.188.0/24
195.234.136.12
209.46.117.168
75.126.200.128/27
46.19.168.0/23
80.66.137.58
37.188.97.188/32
74.63.234.0/24
208.115.214.0/24
81.223.46.0/27
195.54.172.0/23
209.67.98.59
198.37.144.0/20
94.236.119.0/26
217.175.196.0/24
54.214.38.255
208.117.48.0/20
2a04:35c0::/29
136.146.128.64/27
91.211.242.0/24
217.175.193.0/24
185.28.196.0/22
216.113.167.0/24
203.49.69.114
146.88.28.0/24
67.72.99.26
96.43.151.64/28
216.113.188.96/27
96.43.144.64/28
192.254.112.0/20
136.147.46.32/28
185.4.122.0/24
204.75.142.0/24
74.63.236.0/24
216.113.175.103
66.135.213.241
74.63.235.0/24
91.211.243.0/24
